Store/Models/Item.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Store.Models
{
    [Table("Item")]
    public class Item
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Name")]
        [Required]
        [StringLength(225)]
        public string name { get; set; }

        public List<Purchase> purchases { get ; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public int? quantity 
        {
            get {
                    if (purchases != null){
                        return purchases.Sum(a => a.quantity);
                    }
                    else {
                        return 0;
                    }
                }
             set { } 
        }
    }
}

Store/Models/Purchase.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Store.Models
{

    [Table("purchase")]
    public class Purchase
    {
        [Key]
        public int id { get; set; }

        [Display(Name = "Purchase Date")]
        [Required]
        public DateTime purchaseDate { get; set; }

        [Display(Name ="Quantity")]
        [Required]
        public int quantity { get; set; }

        [Display(Name = "Item")]
        [Required]
        public int itemId { get; set; }

        [ForeignKey("itemId")]
        public virtual Item item { get; set; }
    }
}

Store/Models/StoreDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Store.Models
{
    public class StoreDbContext : DbContext
    {
        public DbSet<Item> items { get; set; }
        public DbSet<Purchase> purchases { get; set; }

    }
}

Store/ViewModels/PurchaseItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Store.Models;
namespace Store.ViewModels
{
    public class PurchaseItems
    {
        public List<Item> items { get; set; }
        public Purchase purchase { get; set; }
    }
}

Store/Controllers/ItemController.cs
using Store.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data.Entity;


namespace Store.Controllers
{
    public class ItemController : Controller
    {
        StoreDbContext db = new StoreDbContext();
        // GET: Item
        [HttpGet]
        public ActionResult Index()
        {
            var items = db.items.Include(i => i.purchases).ToList();   

            return View(items);
        }
        [HttpGet]     
        public ActionResult Add() {

            return View();
        }
        [HttpPost]
        public ActionResult Add(Item item) {
            if (!ModelState.IsValid) {
                return View(nameof(Add));
            }
            db.items.Add(item);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // GET: Item/Details/id
        public ActionResult Details(int id)
        {
            Item item = db.items.Include(i=>i.purchases).SingleOrDefault(i=>i.id == id);
            return PartialView(item);
        }

        // item/edit/id
        public ActionResult Edit(int id)
        {
            Item item = db.items.Find(id);

            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            if (!ModelState.IsValid) {

                return View(nameof(Edit), new Item() { id = item.id});
            }
            Item editItem = db.items.Find(item.id);
            editItem.name = item.name;
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        // item/delete/id
        public ActionResult Delete(int id)
        {
            Item item = db.items.Find(id);
            db.items.Remove(item);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Store/Controllers/PurchaseController.cs
using Store.Models;
using Store.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace Store.Controllers
{
    public class PurchaseController : Controller
    {
        StoreDbContext db = new StoreDbContext();
        // GET: Purchase
        public ActionResult Index()
        {
            List<Purchase> purchases = db.purchases.Include(a => a.item).ToList();
            return View(purchases);
        }
        // get : purchase/add
        public ActionResult Add() {

            PurchaseItems purchaseItems = new PurchaseItems();

            purchaseItems.items = db.items.ToList();

            return View(purchaseItems);
        }

        [HttpPost]
        public ActionResult Add(PurchaseItems purchaseItem)
        {
            if (!ModelState.IsValid) {
                return RedirectToAction(nameof(Add));
            }
            db.purchases.Add(purchaseItem.purchase);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Delete(int id) {

            Purchase purchase = db.purchases.Include(a=>a.item).FirstOrDefault(a=>a.id == id);
            Item item = db.items.Find(purchase.itemId);
            item.quantity -= purchase.quantity;
            db.purchases.Remove(purchase);
            db.SaveChanges();
            
            return RedirectToAction(nameof(Index));
        }
    }

}

Store/Views/Item/Add.cshtml
@{
	ViewBag.Title = "Add";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title> Add Item</title>

</head>

<body>
	<div class="mt-3">
		@using (Html.BeginForm())
		{
			<div>

				@Html.Partial("AddEdit")

				<input type="submit" value="Add" class="btn btn-primary" />

				@Html.ActionLink("Cancel", "Index", "Item", new { @class = "btn btn-primary" })

			</div>

		}
	</div>

</body>
</html>

@section scripts{
	@Scripts.Render("~/bundles/jqueryval")
}

Store/Views/Item/AddEdit.cshtml
@model Item
<div class="mb-3 row">
	@Html.LabelFor(a => a.name, new { @class = "col-sm-2 col-form-label" })
	<div class=" col-sm-10">
		@Html.TextBoxFor(a => a.name, new { @class = "form-control" })
		@Html.ValidationMessageFor(a => a.name)
	</div>
</div>

Store/Views/Item/Delete.cshtml
@model Item
	<div>
		<label>Are you Sure ?</label>
		<label>Item id : @Model.id</label>
		<label>Item name : @Model.name</label>
	</div>

Store/Views/Item/Details.cshtml
@model Item

	<div class="row">
		<div class="col-2"> <label>Id:</label></div>
		<div class="col"> <label>@Model.id</label></div>
	</div>
	<div class="row">
		<div class="col-2"> <label>Name:</label></div>
		<div class="col"> <label>@Model.name</label></div>
	</div>
	<div class="row">
		<div class="col-2"> <label>Quantity:</label></div>
		<div class="col"> <label>@Model.quantity</label></div>
	</div>

Store/Views/Item/Edit.cshtml
@{
	ViewBag.Title = "Edit";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Edit</title>
</head>
<body>
	<div class="mt-3">
		@using (Html.BeginForm())
		{

			@Html.Partial("AddEdit")
			<input type="submit" value="Save" class="btn btn-primary" />
			@Html.ActionLink("Cancel", "Index", "Item", new { @class = "btn btn-primary" })
		}
	</div>
</body>
</html>

@section scripts{
	@Scripts.Render("~/bundles/jqueryval")
}

Store/Views/Item/Index.cshtml
@model IEnumerable<Item>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Index </title>
		<link href="~/Content/bootstrap.css" rel="stylesheet" />
	</head>
	<body>
		<div class="mt-3">
			@Html.ActionLink("Add Item", "Add", "item", null, new { @class = "btn btn-primary mb-2" })

			@if (Model != null && Model.Count() > 0)
			{
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<td>Id</td>
							<td>Name</td>
							<td>Quantity</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						@foreach (Item item in Model)
						{
							<tr>
								<td>@item.id</td>
								<td>@item.name</td>
								<td>@item.quantity</td>
								<td>

									<a href="/item/Edit/@item.id" class="btn btn-primary">Edit</a>
									<a class="btn btn-primary" href="/Item/Delete/@item.id"
									   onclick="return confirm('Are you sure?')">Delete</a>

									@Ajax.ActionLink("Details", "Details", "Item",
								   new { id = item.id }, new AjaxOptions
										{
									   UpdateTargetId = "popUpDiv2",
									   InsertionMode = InsertionMode.Replace,
									   HttpMethod = "Get",
									   OnComplete = "myFunction()"
								   }, new { @class = "btn btn-primary" })
								</td>
							</tr>
						}

					</tbody>
				</table>
			}
			else
			{
				<h2> No Items</h2>
			}
		</div>

		@* Details pop up *@
		<div class="modal" tabindex="-1" id="popUpDiv1">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Details</h5>
					</div>
					<div class="modal-body" id="popUpDiv2">
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					</div>
				</div>
			</div>
		</div>
		@* End of details pop up *@
		@section myScripts{
			<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
			<script>
				function myFunction() {
					$("#popUpDiv1").modal("show")
				}
			</script>
		}

	</body>
	</html>

Store/Views/Purchase/Add.cshtml
@model PurchaseItems
@{
	ViewBag.Title = "Add";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title></title>
</head>
<body>
	<div class="mt-3">
		@using (Html.BeginForm())
		{
			<div class="mb-3 row">
				@Html.LabelFor(a => a.purchase.itemId, new { @class = "col-sm-2 col-form-label" })
				<div class=" col-sm-10">

					@Html.DropDownListFor(a => a.purchase.itemId,
						new SelectList(Model.items, "id", "name"), "", new { @class = "form-control" })
					@Html.ValidationMessageFor(a => a.purchase.itemId)
				</div>
			</div>

			<div class="mb-3 row">
				@Html.LabelFor(a => a.purchase.quantity, new { @class = "col-sm-2 col-form-label" })
				<div class=" col-sm-10">
					@Html.TextBoxFor(a => a.purchase.quantity, new { type = "number", min = "1", step = "1", @class = "form-control" })
					@Html.ValidationMessageFor(a => a.purchase.quantity)
				</div>
			</div>

			<div class="mb-3 row">
				@Html.LabelFor(a => a.purchase.purchaseDate, new { @class = "col-sm-2 col-form-label" })
				<div class=" col-sm-10">
					@Html.TextBoxFor(a => a.purchase.purchaseDate, new { type = "date", id = "datePicker", @class = "form-control" })
					@Html.ValidationMessageFor(a => a.purchase.purchaseDate)
				</div>
			</div>

			<div>
				<input type="submit" value="Add Purchase" class="btn btn-primary" />
				@Html.ActionLink("Cancel", "Index", "Item", new { }, new { @class = "btn btn-primary" })
			</div>

			<div>

				@Html.Label("No Items?") @Html.ActionLink("Add Item", "Add", "Item")
			</div>

		}
	</div>
	<script>
		document.getElementById('datePicker').valueAsDate = new Date();
					//document.getElementById('datePicker').min = new Date();
	</script>

</body>
</html>

@section scripts{
	@Scripts.Render("~/bundles/jqueryval")
}

Store/Views/Purchase/Index.cshtml
@model IEnumerable< Purchase>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
	<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title></title>
	</head>
	<body>

		<div class="mt-3">
			@if (Model != null && Model.Count() > 0)
			{
				<table class="table table-bordered table-hover">
					<thead>
						<tr>
							<td>Item Id</td>
							<td>Item Name</td>
							<td>Quantity</td>
							<td>Purchase Date</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
						@foreach (var purchase in Model)
						{
							<tr>
								<td>@purchase.itemId</td>
								<td>@purchase.item.name</td>
								<td>@purchase.quantity</td>
								<td>@purchase.purchaseDate</td>


								<td>

									<a href="/purchase/Delete/@purchase.id" onclick="return confirm('Are you sure?')"
									   class="btn btn-primary">Delete</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
			}
			else
			{
				<h2> No purchased items yet </h2>
				@Html.ActionLink("Add Purchase", "Add", "Purchase", new { }, new { @class = "btn btn-primary" })
			}			@Html.ActionLink("Add Item", "Add", "item", null, new { @class = "btn btn-primary" })

		</div>
	
	</body>
	</html>

Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport">
	<title>@ViewBag.Title - My ASP.NET Application</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")

</head>
<body class="pt-0">

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			@Html.ActionLink("Store", "Index", "Item", null, new { @class = "navbar-brand" })

			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">

					<li class="nav-item">
						@Html.ActionLink("Manage Items", "Index", "Item", null, new { @class = "nav-link active" })
					</li>

					<li class="nav-item">
						@Html.ActionLink("Add Purchase", "Add", "Purchase", null, new { @class = "nav-link active" })
					</li>

					<li class="nav-item">
						@Html.ActionLink("Purchase History", "Index", "Purchase", null, new { @class = "nav-link active" })
					</li>

				</ul>
			</div>
		</div>
	</nav>

	@*<div class="navbar navbar-inverse navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li>@Html.ActionLink("Home", "Index", "Home")</li>
						<li>@Html.ActionLink("About", "About", "Home")</li>
						<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
					</ul>
				</div>
			</div>
		</div>*@



	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)

	
	@RenderSection("myScripts",false)
</body>
</html>